FROM osrf/ros:indigo-desktop-full
# install ros tutorials packages
RUN apt-get update && apt-get install -y \
  ros-indigo-ros-tutorials \
  ros-indigo-common-tutorials \
  && rm -rf /var/lib/opt/lists

